import {createActions} from "reduxsauce";

const {Types: NomenclatorTypes, Creators: NomenclatorCreators} = createActions({
    loadNomenclatorsRequest: null,
    loadNomenclatorsSuccess: ["nomenclators"],
    loadNomenclatorsFailure: ["error"],
    select: ["selected"],
    loadData: ["nomenclatorname"],
    loadDataSuccess: ["nomenclator"],
    loadDataFailure: null,
    create: ["record"],
    createSuccess: null,
    createFailure: null,
    edit: ["record"],
    editSuccess: null,
    editFailure: null,
    remove: ["nomenclatorname"],
    removeSuccess: null,
    removeFailure: null,
    goToList: ["path"],
    updatePageData: ["data"],
    updateAppliedFilters: ["filters"],
    clearSelected: null,
    addCommand: null,
    editCommand: null,
    loadBanks: null,
    loadBanksSuccess: ["banks"],
    loadBanksFailure: null,
    loadDepartments: null,
    loadDepartmentsSuccess: ["departments"],
    loadDepartmentsFailure: null,
    loadAccountTypes: null,
    loadAccountTypesSuccess: ["accountTypes"],
    loadAccountTypesFailure: null,
    loadPolicyCompanies: null,
    loadPolicyCompaniesSuccess: ["companies"],
    loadPolicyCompaniesFailure: null,
    reset: null
}, {prefix: "NOMENCLATOR_"});

export {NomenclatorTypes, NomenclatorCreators};
